import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
// import ThemeToggle from "@/components/theme-toggle"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CareerGuideAi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider >
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ThemeProvider
         
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Header/>
        <main>{children}</main>
        <Toaster/>
         <div className="fixed bottom-4 right-4 z-50">
    {/* <ThemeToggle suppressHydrationWarning /> */}
  </div>
        <footer className=" fixed bottom-0 w-full bg-muted/50 py-2 ">
          <div className="container mx-auto px-6 text-center text-gray-300">
            <p>
              All rights reserved
            </p>
          </div>
        </footer>
        </ThemeProvider >
      </body>
    </html>
    </ClerkProvider>
  );
}
